version: '3.8'

services:
  frontend:
    build: 
      context: ./code
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./code/.env.production
    environment:
      - NODE_ENV=production
    restart: always
    

  admin:
    build: 
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - ./code/.env.production  
    environment:
      - NODE_ENV=production
    restart: always
    
